### ISSUE TITLE
Apply Theme to Modal

### ISSUE THREAD

**Issue by nikolasdas** [NativeScript/theme#194]
I'm trying to change the Theme from inside a modal using setTheme/toggleTheme. It works for the main view and the change get applied immediately. But the modal does not change until closing and reopening. Am I doing something wrong?
(Using version 2.1.2)

**Comment by bundyo** [comment]
I think this is a limitation of the modal dialogs. @MartoYankov, what do you think?

**Comment by bundyo** [comment]
This has nothing to do with the theme API. When using HMR and CSS changes, the updates are not applied on the modal while it is open - you need to close and reopen it to see the changes, so it should be something in the core modules, hence the question. :slightly_smiling_face:

**Comment by vchimev** [comment]
Currently, the framework does not set the `ns-dark/ns-light` CSS classes on modal root views.
It is in progress and I hope to be available soon after the official release.

**Comment by bundyo** [comment]
You can probably do something like this until then - might help:

```css
.ns-dark .ns-modal {
    class: ns-dark;
}
```

Or it might break your app. :smile:

**Comment by vchimev** [comment]
There are at least two tasks here:
- assign the system CSS classes to root modal views: https://github.com/NativeScript/NativeScript/pull/8084
- implement the respective classes in the theme.

**Comment by bundyo** [comment]
The respective classes should be working in the theme - I had to add some specific overrides, since they weren't working in 6.2. :)

**Comment by vchimev** [comment]
Changes have done, to be released ...

**Comment by farfromrefug** [comment]
@vchimev @vakrilov i actually still see the issue in 6.4.1 on android.

I am using 
* @nativescript/core: rc 
* @nativescript/theme: 2.3.0

You can see the behavior in [this](https://github.com/farfromrefug/ns-forecastie) app project. 
Sorry i don'ave a simpler project to reproduce.
* dark/light style is set for `page` in the app [scss](https://github.com/farfromrefug/ns-forecastie/blob/master/app/app.scss#L74)
* it is correctly applied to the root window.
* click on the search icon => modal window [here](https://github.com/farfromrefug/ns-forecastie/blob/master/app/WeatherPage.svelte#L264). 
* the opened window is white which and the status bar property applied are for white theme. Which means [this](https://github.com/farfromrefug/ns-forecastie/blob/master/app/app.scss#L74) was not applied

Dont know if you want me to open a new issue or if this one is good.
