### ISSUE TITLE
SCSS installation causes compilation issue

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#79]
> /app/scss/core.dark.android.scss SASS CSS pre-processing failed. Error: Error: File to import not found or unreadable: ./scss/themes/core/dark

**Comment by NathanWalker** [comment]
Repro:
```
tns create sample --template https://github.com/NativeScript/template-hello-world-ts.git
npm i nativescript-dev-sass --save-dev
```
Modify `app.css` to `app.scss`
```
npm i nativescript-theme-core --save
tns run android
```

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/theme/issues/78

**Comment by NathanWalker** [comment]
Fixed with `0.1.1`

**Comment by JohnGalt1717** [comment]
Using 0.1.3 this still happens. Run the default tns create xyz -ng
Remove nativescript-theme-core and then add it back.

Nothing will be in the right spot. (all of the core.xx.xxx.scss will be put in the /app folder instead of the /css folder, the app.scss file will not be updated properly, and the theme-core--scss folder will be put in /app instead of in /app/css too)

**Comment by JohnGalt1717** [comment]
Moving those into the right spot throws an error on debug saying that it can't find ~/css/core.light.scss because there is only a core.light.android.scss etc.

**Comment by NathanWalker** [comment]
@NathanaelA could you verify?

**Comment by NathanaelA** [comment]
Well a couple things.  @NathanWalker 
1. The main scss is put in the root folder, not in the /css/ (by design).     Everything probably would break if you move it manually.   We could move everything scss related into the css folder if you wanted...
2. This might change drastically if we are eliminating the post_install script...  That needs to be determined before this can be figured out.

**Comment by NathanWalker** [comment]
Agreed. @JohnGalt1717 We definitely don't want anyone moving things around manually, you shouldn't need to do that at all. We'll discuss and update here when we know more regarding some redesign around our post installer.

**Comment by JohnGalt1717** [comment]
So here's the issues as I see them:

1. core.dark.android.css etc. get put in the /app/css folder. The SCSS files that create those get put in the /app folder thus they can't be updated by compiling the scss files because it's the wrong directory. (same with _bootstrap-map.scss which doesn't appear to do anything)

2. The theme-core-scss is also in /app instead of as a sub directory of /app/css which makes the project messy because you end up with css in two separate places that's all boilerplate.

3. If you use tns create xxx -ng it creates css files. These will NOT get updated to scss files when you add the sass compiler and there is no obvious indication on how to regen or even to know that on another machine where npm install is run for the first time from a get from source control that it will automatically generate scss files, so you've proceeded to update .css and now you have am ess of scss files in the wrong spot in contradiction with your css and this will happen any time npm install or npm update is run on the project thus making a mess of the project in the process.

So I suggest:

1. ALL automatically created .scss should go into the /app/css folder along with their .css results and theme-core-scss should go as a sub folder in there.
2. The install process for themes and scss should check for eachother and automatically create the .scss on install. So if themes is installed and the user adds scss support, then it should automatically add the .scss files for themes.
